# E-Commerce Logistics & Sales Analyzer
##### The Scenario: You are given three separate datasets: "Customer Profiles" (age, region, subscription tier), "Product Catalog" (category, weight, unit price), and "Order Transactions" (who bought what, when, and delivery times).

In [1]:
import pandas as pd
customer_df = pd.read_csv('customers.csv')
product_df = pd.read_csv('products.csv')
ord_jan_df = pd.read_csv('orders_jan.csv')
ord_feb_df = pd.read_csv('orders_feb.csv')

##### Combining Datasets: You must use pd.concat() to stitch together the order transactions from "January" and "February". Then, use pd.merge() to join the combined 'Order Transactions' table with the 'Product Catalog' table so you know the category and price of the item purchased, acting like a SQL left join.

In [2]:
order_df = pd.concat([ord_jan_df,ord_feb_df],ignore_index=True)
order_df

,Transaction_ID,cust_ID,Product_ID,Quantity,Order_Date,Delivery_Days,Warehouse_Route_ID
0,T00001,C0546,P0146,4,2024-01-26,2,WH-A1
1,T00002,C0609,P0938,1,2024-01-22,6,WH-C4
2,T00003,C0169,P0057,3,2024-01-07,6,WH-B3
3,T00004,C0681,P0723,1,2024-01-10,1,WH-A9
4,T00005,C0663,P0780,3,2024-01-28,1,WH-A7
...,...,...,...,...,...,...,...
1995,T01996,C0637,P0623,3,2024-02-19,3,WH-C2
1996,T01997,C0716,P0210,3,2024-02-09,4,WH-A8
1997,T01998,C0573,P0513,1,2024-02-09,1,WH-B4
1998,T01999,C0762,P0058,3,2024-02-13,2,WH-C9
1999,T02000,C0810,P0093,4,2024-02-06,5,WH-B6

In [3]:
merges_df = pd.merge(order_df,product_df,on='Product_ID',how='left')
merges_df

,Transaction_ID,cust_ID,Product_ID,Quantity,Order_Date,Delivery_Days,Warehouse_Route_ID,Product_Category,Weight_kg,Unit_Price
0,T00001,C0546,P0146,4,2024-01-26,2,WH-A1,Home & Garden,11.97,403.69
1,T00002,C0609,P0938,1,2024-01-22,6,WH-C4,Toys,11.11,152.34
2,T00003,C0169,P0057,3,2024-01-07,6,WH-B3,Clothing,10.97,8.16
3,T00004,C0681,P0723,1,2024-01-10,1,WH-A9,Electronics,11.15,488.40
4,T00005,C0663,P0780,3,2024-01-28,1,WH-A7,Sports,7.34,476.43
...,...,...,...,...,...,...,...,...,...,...
1995,T01996,C0637,P0623,3,2024-02-19,3,WH-C2,Toys,7.38,298.92
1996,T01997,C0716,P0210,3,2024-02-09,4,WH-A8,Toys,4.08,55.91
1997,T01998,C0573,P0513,1,2024-02-09,1,WH-B4,Toys,2.94,85.87
1998,T01999,C0762,P0058,3,2024-02-13,2,WH-C9,Home & Garden,14.51,489.29
1999,T02000,C0810,P0093,4,2024-02-06,5,WH-B6,Sports,5.60,85.69

##### Modifying DataFrames: You create a new calculated column called Total_Revenue by multiplying the Quantity column by the Unit_Price column. Use .drop() to remove redundant warehouse routing IDs, and use .rename() to fix inconsistently capitalized columns (e.g., changing cust_ID to Customer_ID).

In [4]:
merges_df['Total_Revenue'] = merges_df['Quantity']*merges_df['Unit_Price']
merges_df

,Transaction_ID,cust_ID,Product_ID,Quantity,Order_Date,Delivery_Days,Warehouse_Route_ID,Product_Category,Weight_kg,Unit_Price,Total_Revenue
0,T00001,C0546,P0146,4,2024-01-26,2,WH-A1,Home & Garden,11.97,403.69,1614.76
1,T00002,C0609,P0938,1,2024-01-22,6,WH-C4,Toys,11.11,152.34,152.34
2,T00003,C0169,P0057,3,2024-01-07,6,WH-B3,Clothing,10.97,8.16,24.48
3,T00004,C0681,P0723,1,2024-01-10,1,WH-A9,Electronics,11.15,488.40,488.40
4,T00005,C0663,P0780,3,2024-01-28,1,WH-A7,Sports,7.34,476.43,1429.29
...,...,...,...,...,...,...,...,...,...,...,...
1995,T01996,C0637,P0623,3,2024-02-19,3,WH-C2,Toys,7.38,298.92,896.76
1996,T01997,C0716,P0210,3,2024-02-09,4,WH-A8,Toys,4.08,55.91,167.73
1997,T01998,C0573,P0513,1,2024-02-09,1,WH-B4,Toys,2.94,85.87,85.87
1998,T01999,C0762,P0058,3,2024-02-13,2,WH-C9,Home & Garden,14.51,489.29,1467.87
1999,T02000,C0810,P0093,4,2024-02-06,5,WH-B6,Sports,5.60,85.69,342.76

In [5]:
merges_df.drop('Warehouse_Route_ID',axis=1,inplace=True)
merges_df

,Transaction_ID,cust_ID,Product_ID,Quantity,Order_Date,Delivery_Days,Product_Category,Weight_kg,Unit_Price,Total_Revenue
0,T00001,C0546,P0146,4,2024-01-26,2,Home & Garden,11.97,403.69,1614.76
1,T00002,C0609,P0938,1,2024-01-22,6,Toys,11.11,152.34,152.34
2,T00003,C0169,P0057,3,2024-01-07,6,Clothing,10.97,8.16,24.48
3,T00004,C0681,P0723,1,2024-01-10,1,Electronics,11.15,488.40,488.40
4,T00005,C0663,P0780,3,2024-01-28,1,Sports,7.34,476.43,1429.29
...,...,...,...,...,...,...,...,...,...,...
1995,T01996,C0637,P0623,3,2024-02-19,3,Toys,7.38,298.92,896.76
1996,T01997,C0716,P0210,3,2024-02-09,4,Toys,4.08,55.91,167.73
1997,T01998,C0573,P0513,1,2024-02-09,1,Toys,2.94,85.87,85.87
1998,T01999,C0762,P0058,3,2024-02-13,2,Home & Garden,14.51,489.29,1467.87
1999,T02000,C0810,P0093,4,2024-02-06,5,Sports,5.60,85.69,342.76

In [6]:
merges_df.rename(columns={'cust_ID':'Customer_ID'},inplace=True)
merges_df

,Transaction_ID,Customer_ID,Product_ID,Quantity,Order_Date,Delivery_Days,Product_Category,Weight_kg,Unit_Price,Total_Revenue
0,T00001,C0546,P0146,4,2024-01-26,2,Home & Garden,11.97,403.69,1614.76
1,T00002,C0609,P0938,1,2024-01-22,6,Toys,11.11,152.34,152.34
2,T00003,C0169,P0057,3,2024-01-07,6,Clothing,10.97,8.16,24.48
3,T00004,C0681,P0723,1,2024-01-10,1,Electronics,11.15,488.40,488.40
4,T00005,C0663,P0780,3,2024-01-28,1,Sports,7.34,476.43,1429.29
...,...,...,...,...,...,...,...,...,...,...
1995,T01996,C0637,P0623,3,2024-02-19,3,Toys,7.38,298.92,896.76
1996,T01997,C0716,P0210,3,2024-02-09,4,Toys,4.08,55.91,167.73
1997,T01998,C0573,P0513,1,2024-02-09,1,Toys,2.94,85.87,85.87
1998,T01999,C0762,P0058,3,2024-02-13,2,Home & Garden,14.51,489.29,1467.87
1999,T02000,C0810,P0093,4,2024-02-06,5,Sports,5.60,85.69,342.76

##### Applying Functions: You write a custom function (or use a lambda) and apply it via .apply() to categorize the Delivery_Days column into delivery performance buckets: "Early" (1-2 days), "On-Time" (3-4 days), or "Delayed" (5+ days).

In [7]:
merges_df['delivery_performance'] = merges_df['Delivery_Days'].apply(
    lambda x: 'Early' if x <= 2
    else 'On-Time' if x <= 4
    else 'Delayed'
)
merges_df

,Transaction_ID,Customer_ID,Product_ID,Quantity,Order_Date,Delivery_Days,Product_Category,Weight_kg,Unit_Price,Total_Revenue,delivery_performance
0,T00001,C0546,P0146,4,2024-01-26,2,Home & Garden,11.97,403.69,1614.76,Early
1,T00002,C0609,P0938,1,2024-01-22,6,Toys,11.11,152.34,152.34,Delayed
2,T00003,C0169,P0057,3,2024-01-07,6,Clothing,10.97,8.16,24.48,Delayed
3,T00004,C0681,P0723,1,2024-01-10,1,Electronics,11.15,488.40,488.40,Early
4,T00005,C0663,P0780,3,2024-01-28,1,Sports,7.34,476.43,1429.29,Early
...,...,...,...,...,...,...,...,...,...,...,...
1995,T01996,C0637,P0623,3,2024-02-19,3,Toys,7.38,298.92,896.76,On-Time
1996,T01997,C0716,P0210,3,2024-02-09,4,Toys,4.08,55.91,167.73,On-Time
1997,T01998,C0573,P0513,1,2024-02-09,1,Toys,2.94,85.87,85.87,Early
1998,T01999,C0762,P0058,3,2024-02-13,2,Home & Garden,14.51,489.29,1467.87,Early
1999,T02000,C0810,P0093,4,2024-02-06,5,Sports,5.60,85.69,342.76,Delayed

##### Grouping and Aggregation: Using .groupby(), you group the data by Product_Category and use .agg() to find the total revenue generated, the average delivery days, and the unique count of Customer_IDs who purchased from that category.

In [8]:
summary = merges_df.groupby('Product_Category').agg(
    Total_revenue_generated = ('Total_Revenue','sum'),
    The_average_delivery_days = ('Delivery_Days','mean'),
    The_unique_count = ('Customer_ID','nunique')
)
print(summary)

                  Total_revenue_generated  The_average_delivery_days  \
Product_Category
Clothing                        236216.30                   4.005764
Electronics                     291529.29                   3.960688
Home & Garden                   318433.12                   4.009324
Sports                          311298.28                   3.847255
Toys                            300972.12                   3.871859

                  The_unique_count
Product_Category
Clothing                       289
Electronics                    333
Home & Garden                  342
Sports                         346
Toys                           316

##### Reshaping and Pivoting: Finally, you use pd.pivot_table() to create a business-reporting matrix showing "Customer Region" as rows, "Delivery Performance" (Early/On-Time/Delayed) as columns, and the "Total Revenue" as the values.

In [10]:
merges_df = pd.merge(merges_df, customer_df,on='Customer_ID',how='left')
merges_df

,Transaction_ID,Customer_ID,Product_ID,Quantity,Order_Date,Delivery_Days,Product_Category,Weight_kg,Unit_Price,Total_Revenue,delivery_performance,Age,Region,Subscription_Tier
0,T00001,C0546,P0146,4,2024-01-26,2,Home & Garden,11.97,403.69,1614.76,Early,70,South,Premium
1,T00002,C0609,P0938,1,2024-01-22,6,Toys,11.11,152.34,152.34,Delayed,41,North,Basic
2,T00003,C0169,P0057,3,2024-01-07,6,Clothing,10.97,8.16,24.48,Delayed,49,East,Premium
3,T00004,C0681,P0723,1,2024-01-10,1,Electronics,11.15,488.40,488.40,Early,42,South,Basic
4,T00005,C0663,P0780,3,2024-01-28,1,Sports,7.34,476.43,1429.29,Early,52,South,Basic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,T01996,C0637,P0623,3,2024-02-19,3,Toys,7.38,298.92,896.76,On-Time,43,East,Plus
1996,T01997,C0716,P0210,3,2024-02-09,4,Toys,4.08,55.91,167.73,On-Time,70,North,Basic
1997,T01998,C0573,P0513,1,2024-02-09,1,Toys,2.94,85.87,85.87,Early,33,North,Basic
1998,T01999,C0762,P0058,3,2024-02-13,2,Home & Garden,14.51,489.29,1467.87,Early,24,North,Premium
1999,T02000,C0810,P0093,4,2024-02-06,5,Sports,5.60,85.69,342.76,Delayed,54,West,Basic

In [11]:
pivot_df = pd.pivot_table(
    merges_df,
    index = 'Region',
    columns = 'delivery_performance',
    values = 'Total_Revenue',
    aggfunc = 'sum'
)
print(pivot_df)

delivery_performance    Delayed      Early    On-Time
Region
East                  165532.82   91495.83  102829.30
North                 168913.17  115843.80  125378.86
South                 157531.94  112139.58  102640.26
West                  129061.42  111503.35   75578.78