# Music Streaming Habits Analyzer
##### The Scenario: You are given three separate datasets: "User Demographics", "Track Metadata" (artist, genre, duration), and "Listening History" (who listened to what, and when).

In [65]:
import pandas as pd
df_user = pd.read_csv('user_demographics.csv')
df_track = pd.read_csv('track_metadata.csv')
df_listening_q1 = pd.read_csv('listening_history_q1.csv')
df_listening_q2 = pd.read_csv('listening_history_q2.csv')

##### Combining Datasets: You must use pd.concat() to stitch together listening history from Q1 and Q2. Then, use pd.merge() to join the 'Listening History' table with the 'Track Metadata' table so you know the genre of the song played, acting like a SQL left join.

In [66]:
listening_history = pd.concat([df_listening_q1,df_listening_q2],ignore_index=True)
listening_history

      listen_id  usr_ref_id  trk_ref_id            timestamp
0             1         167         146  2025-01-23 22:19:45
1             3          90         105  2025-01-06 15:32:21
2             5          39         119  2025-02-12 11:12:04
3             6         126         149  2025-03-05 19:52:42
4             8         173         101  2025-01-04 05:56:14
...         ...         ...         ...                  ...
1495       1494         175         126  2025-06-15 07:30:32
1496       1495         165         101  2025-05-22 13:18:12
1497       1496          49         128  2025-06-13 22:29:31
1498       1497         120         137  2025-04-26 02:20:18
1499       1500         156         129  2025-05-10 23:01:51

[1500 rows x 4 columns]

In [67]:
listening_history.rename(columns={'trk_ref_id':'track_id'},inplace=True)
merge_df = pd.merge(listening_history, df_track,on='track_id',how='left')
merge_df

,listen_id,usr_ref_id,track_id,timestamp,artist_name,Genre,length_in_ms,internal_db_id
0,1,167,146,2025-01-23 22:19:45,Artist_46,Electronic,121062,119870
1,3,90,105,2025-01-06 15:32:21,Artist_5,Electronic,285983,138102
2,5,39,119,2025-02-12 11:12:04,Artist_19,Hip-Hop,134397,625830
3,6,126,149,2025-03-05 19:52:42,Artist_49,Pop,272617,334677
4,8,173,101,2025-01-04 05:56:14,Artist_1,Pop,205999,897606
...,...,...,...,...,...,...,...,...
1495,1494,175,126,2025-06-15 07:30:32,Artist_26,Rock,298352,319930
1496,1495,165,101,2025-05-22 13:18:12,Artist_1,Pop,205999,897606
1497,1496,49,128,2025-06-13 22:29:31,Artist_28,Classical,267851,617313
1498,1497,120,137,2025-04-26 02:20:18,Artist_37,Hip-Hop,259407,257504
1499,1500,156,129,2025-05-10 23:01:51,Artist_29,Rock,275538,314532

##### Modifying DataFrames: You create a new calculated column called Minutes_Played by dividing the Milliseconds column by 60,000. Use .drop() to clear redundant system ID columns and .rename() poorly named columns.

In [68]:
merge_df['Minutes_Played'] = merge_df['length_in_ms'] / 60000
merge_df

,listen_id,usr_ref_id,track_id,timestamp,artist_name,Genre,length_in_ms,internal_db_id,Minutes_Played
0,1,167,146,2025-01-23 22:19:45,Artist_46,Electronic,121062,119870,2.017700
1,3,90,105,2025-01-06 15:32:21,Artist_5,Electronic,285983,138102,4.766383
2,5,39,119,2025-02-12 11:12:04,Artist_19,Hip-Hop,134397,625830,2.239950
3,6,126,149,2025-03-05 19:52:42,Artist_49,Pop,272617,334677,4.543617
4,8,173,101,2025-01-04 05:56:14,Artist_1,Pop,205999,897606,3.433317
...,...,...,...,...,...,...,...,...,...
1495,1494,175,126,2025-06-15 07:30:32,Artist_26,Rock,298352,319930,4.972533
1496,1495,165,101,2025-05-22 13:18:12,Artist_1,Pop,205999,897606,3.433317
1497,1496,49,128,2025-06-13 22:29:31,Artist_28,Classical,267851,617313,4.464183
1498,1497,120,137,2025-04-26 02:20:18,Artist_37,Hip-Hop,259407,257504,4.323450
1499,1500,156,129,2025-05-10 23:01:51,Artist_29,Rock,275538,314532,4.592300

In [69]:
merge_df.drop('internal_db_id',axis=1,inplace=True)
merge_df

,listen_id,usr_ref_id,track_id,timestamp,artist_name,Genre,length_in_ms,Minutes_Played
0,1,167,146,2025-01-23 22:19:45,Artist_46,Electronic,121062,2.017700
1,3,90,105,2025-01-06 15:32:21,Artist_5,Electronic,285983,4.766383
2,5,39,119,2025-02-12 11:12:04,Artist_19,Hip-Hop,134397,2.239950
3,6,126,149,2025-03-05 19:52:42,Artist_49,Pop,272617,4.543617
4,8,173,101,2025-01-04 05:56:14,Artist_1,Pop,205999,3.433317
...,...,...,...,...,...,...,...,...
1495,1494,175,126,2025-06-15 07:30:32,Artist_26,Rock,298352,4.972533
1496,1495,165,101,2025-05-22 13:18:12,Artist_1,Pop,205999,3.433317
1497,1496,49,128,2025-06-13 22:29:31,Artist_28,Classical,267851,4.464183
1498,1497,120,137,2025-04-26 02:20:18,Artist_37,Hip-Hop,259407,4.323450
1499,1500,156,129,2025-05-10 23:01:51,Artist_29,Rock,275538,4.592300

In [70]:
merge_df.rename(columns={'usr_ref_id':'user_id'},inplace=True)
merge_df

,listen_id,user_id,track_id,timestamp,artist_name,Genre,length_in_ms,Minutes_Played
0,1,167,146,2025-01-23 22:19:45,Artist_46,Electronic,121062,2.017700
1,3,90,105,2025-01-06 15:32:21,Artist_5,Electronic,285983,4.766383
2,5,39,119,2025-02-12 11:12:04,Artist_19,Hip-Hop,134397,2.239950
3,6,126,149,2025-03-05 19:52:42,Artist_49,Pop,272617,4.543617
4,8,173,101,2025-01-04 05:56:14,Artist_1,Pop,205999,3.433317
...,...,...,...,...,...,...,...,...
1495,1494,175,126,2025-06-15 07:30:32,Artist_26,Rock,298352,4.972533
1496,1495,165,101,2025-05-22 13:18:12,Artist_1,Pop,205999,3.433317
1497,1496,49,128,2025-06-13 22:29:31,Artist_28,Classical,267851,4.464183
1498,1497,120,137,2025-04-26 02:20:18,Artist_37,Hip-Hop,259407,4.323450
1499,1500,156,129,2025-05-10 23:01:51,Artist_29,Rock,275538,4.592300

##### Applying Functions: You write a custom function (or use a lambda) and apply it via .apply() to categorize the time of day into "Morning", "Afternoon", "Evening" and "Night" based on the timestamp.

In [71]:
merge_df['time_categorize'] = merge_df['timestamp'].apply(
    lambda x: 'Morning' if 0 <= pd.to_datetime(x).hour < 12 else 
    'Afternoon' if 12 <= pd.to_datetime(x).hour < 17 else 
    'Evening' if 17 <= pd.to_datetime(x).hour < 21 else 'Night'
)
merge_df

,listen_id,user_id,track_id,timestamp,artist_name,Genre,length_in_ms,Minutes_Played,time_categorize
0,1,167,146,2025-01-23 22:19:45,Artist_46,Electronic,121062,2.017700,Night
1,3,90,105,2025-01-06 15:32:21,Artist_5,Electronic,285983,4.766383,Afternoon
2,5,39,119,2025-02-12 11:12:04,Artist_19,Hip-Hop,134397,2.239950,Morning
3,6,126,149,2025-03-05 19:52:42,Artist_49,Pop,272617,4.543617,Evening
4,8,173,101,2025-01-04 05:56:14,Artist_1,Pop,205999,3.433317,Morning
...,...,...,...,...,...,...,...,...,...
1495,1494,175,126,2025-06-15 07:30:32,Artist_26,Rock,298352,4.972533,Morning
1496,1495,165,101,2025-05-22 13:18:12,Artist_1,Pop,205999,3.433317,Afternoon
1497,1496,49,128,2025-06-13 22:29:31,Artist_28,Classical,267851,4.464183,Night
1498,1497,120,137,2025-04-26 02:20:18,Artist_37,Hip-Hop,259407,4.323450,Morning
1499,1500,156,129,2025-05-10 23:01:51,Artist_29,Rock,275538,4.592300,Night

##### Grouping and Aggregation: Using .groupby(), you group the data by 'Genre' and use .agg() to find the total minutes played, the average song duration, and the unique count of listeners for each genre.

In [72]:
summary = merge_df.groupby('Genre').agg(
    Total_minutes_played = ('Minutes_Played','sum'),
    Average_song_duration = ('Minutes_Played','mean'),
    The_unique_count = ('user_id','nunique')
)
print(summary)

            Total_minutes_played  Average_song_duration  The_unique_count
Genre
Classical             216.033783               4.500704                43
Electronic           1320.180167               3.636860               164
Hip-Hop              1089.167967               3.821642               154
Jazz                  569.446450               3.409859               117
Pop                  1069.306017               3.712868               162
Rock                 1317.886817               3.776180               170

##### Reshaping and Pivoting: Finally, you use pd.pivot_table() to create a heat-map-ready matrix showing "User Age Group" as rows, "Music Genre" as columns, and "Total Listens" as the values.

In [73]:
merge_df = pd.merge(merge_df, df_user,on='user_id',how='left')
merge_df.rename(columns={'User Age Group':'user_age_group'},inplace=True)
merge_df

,listen_id,user_id,track_id,timestamp,artist_name,Genre,length_in_ms,Minutes_Played,time_categorize,user_age_group,subscription_tier,sys_user_hash
0,1,167,146,2025-01-23 22:19:45,Artist_46,Electronic,121062,2.017700,Night,45-54,Premium,usr_4734
1,3,90,105,2025-01-06 15:32:21,Artist_5,Electronic,285983,4.766383,Afternoon,35-44,Free,usr_5324
2,5,39,119,2025-02-12 11:12:04,Artist_19,Hip-Hop,134397,2.239950,Morning,18-24,Premium,usr_8634
3,6,126,149,2025-03-05 19:52:42,Artist_49,Pop,272617,4.543617,Evening,45-54,Free,usr_3067
4,8,173,101,2025-01-04 05:56:14,Artist_1,Pop,205999,3.433317,Morning,25-34,Free,usr_6438
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,1494,175,126,2025-06-15 07:30:32,Artist_26,Rock,298352,4.972533,Morning,45-54,Free,usr_6803
1496,1495,165,101,2025-05-22 13:18:12,Artist_1,Pop,205999,3.433317,Afternoon,35-44,Free,usr_1403
1497,1496,49,128,2025-06-13 22:29:31,Artist_28,Classical,267851,4.464183,Night,25-34,Free,usr_4520
1498,1497,120,137,2025-04-26 02:20:18,Artist_37,Hip-Hop,259407,4.323450,Morning,25-34,Premium,usr_1888
1499,1500,156,129,2025-05-10 23:01:51,Artist_29,Rock,275538,4.592300,Night,18-24,Free,usr_9189

In [76]:
pivot_df = pd.pivot_table(
    merge_df,
    index = 'user_age_group',
    columns = 'Genre',
    values = 'track_id',
    aggfunc = 'count'
)
print(pivot_df)

Genre           Classical  Electronic  Hip-Hop  Jazz  Pop  Rock
user_age_group
18-24                  11          69       65    27   66    72
25-34                   8          70       61    32   58    58
35-44                   8          59       54    32   58    72
45-54                  13          98       56    44   53    91
55+                     8          67       49    32   53    56