# Messy E-Commerce Customer Database Rescue

##### The Scenario: The company database crashed, and the backup data is a mess. You must clean the "Orders" dataset.

In [16]:
import pandas as pd
df = pd.read_csv('ecommerce.csv')
df

,id,customer name,email,purchase date,price,trx,shipping state
0,NaN,port beckwith,pbeckwith94@geocities.com,30 Jul 2025,$460.25,548f8041-6317-4388-8dce-fe6de027505c,Argentina
1,689.0,kimmy haborn,khabornj4@google.es,pending,$539.17,NaN,Panama
2,414.0,matthias calcutt,mcalcuttbh@freewebs.com,11/17/2025,$534.17,4a22264d-4c87-4f9d-b4a5-99e343cb768e,Brazil
3,789.0,ALGERNON NIAVES,aniaveslw@wunderground.com,2025-09-20,$345.84,83a9aa51-0a17-4fd8-a7c3-46a87c019f7b,Philippines
4,NaN,kynthia mcquirter,kmcquirter6s@yellowbook.com,unknown,$283.29,29c1f562-82cb-40d1-97aa-a467feeb24d8,Indonesia
...,...,...,...,...,...,...,...
1095,467.0,ALLISTER MELLOWS,amellowscy@vimeo.com,2025-11-06,$127.81,7dac3d2e-cfce-423b-b34c-24c1efa35950,NaN
1096,122.0,carl lamey,clamey3d@php.net,17 Mar 2025,$500.37,a900e75e-5035-4357-824e-d82f8db6a607,Armenia
1097,NaN,CYMBRE COCKRILL,ccockrill8b@joomla.org,04 Jul 2025,$482.79,98d998ca-0b37-4898-ae25-ab85c4d981db,Portugal
1098,NaN,brynna petrie,bpetriec4@nhs.uk,15 Jul 2025,$780.39,39d7652c-fe34-4e66-bf90-b5fb2cfbbf2f,China
1099,NaN,tildy worlock,tworlocknw@disqus.com,10 Jan 2026,$173.04,6f79120f-5a4a-4de9-a201-481446647525,Indonesia

##### Handling Missing Data: The dataset is riddled with NaNs. You must use .dropna() to remove rows completely missing an Order ID, .fillna() to replace missing shipping states and transaction with "Unknown" that were lost during export.

In [17]:
df.dropna(subset=['id'],inplace=True)
df

,id,customer name,email,purchase date,price,trx,shipping state
1,689.0,kimmy haborn,khabornj4@google.es,pending,$539.17,NaN,Panama
2,414.0,matthias calcutt,mcalcuttbh@freewebs.com,11/17/2025,$534.17,4a22264d-4c87-4f9d-b4a5-99e343cb768e,Brazil
3,789.0,ALGERNON NIAVES,aniaveslw@wunderground.com,2025-09-20,$345.84,83a9aa51-0a17-4fd8-a7c3-46a87c019f7b,Philippines
5,760.0,hayes kleewein,hkleeweinl3@kickstarter.com,2025-12-30,$275.30,f91b1691-2e28-486d-82eb-1a81cba02f98,Germany
6,97.0,SUSANNE CUMMINS,scummins2o@paypal.com,unknown,$602.31,NaN,Vietnam
...,...,...,...,...,...,...,...
1092,872.0,shawn hengoed,shengoedo7@ustream.tv,pending,$179.86,506a5235-eec5-493e-ab86-392840d8dd9b,China
1093,88.0,maridel rogeron,mrogeron2f@google.de,unknown,$380.12,0da184d0-4c09-4d6b-8d54-cc0f0980fa0e,NaN
1094,331.0,britteny euesden,beuesden96@mayoclinic.com,pending,$699.39,37d4d2d8-06e9-4304-aa87-cecb84d30a95,Peru
1095,467.0,ALLISTER MELLOWS,amellowscy@vimeo.com,2025-11-06,$127.81,7dac3d2e-cfce-423b-b34c-24c1efa35950,NaN
1096,122.0,carl lamey,clamey3d@php.net,17 Mar 2025,$500.37,a900e75e-5035-4357-824e-d82f8db6a607,Armenia

In [18]:
df['shipping state'] = df['shipping state'].fillna('Unknown')
df['trx'] = df['trx'].fillna('Unknown')
df

,id,customer name,email,purchase date,price,trx,shipping state
1,689.0,kimmy haborn,khabornj4@google.es,pending,$539.17,Unknown,Panama
2,414.0,matthias calcutt,mcalcuttbh@freewebs.com,11/17/2025,$534.17,4a22264d-4c87-4f9d-b4a5-99e343cb768e,Brazil
3,789.0,ALGERNON NIAVES,aniaveslw@wunderground.com,2025-09-20,$345.84,83a9aa51-0a17-4fd8-a7c3-46a87c019f7b,Philippines
5,760.0,hayes kleewein,hkleeweinl3@kickstarter.com,2025-12-30,$275.30,f91b1691-2e28-486d-82eb-1a81cba02f98,Germany
6,97.0,SUSANNE CUMMINS,scummins2o@paypal.com,unknown,$602.31,Unknown,Vietnam
...,...,...,...,...,...,...,...
1092,872.0,shawn hengoed,shengoedo7@ustream.tv,pending,$179.86,506a5235-eec5-493e-ab86-392840d8dd9b,China
1093,88.0,maridel rogeron,mrogeron2f@google.de,unknown,$380.12,0da184d0-4c09-4d6b-8d54-cc0f0980fa0e,Unknown
1094,331.0,britteny euesden,beuesden96@mayoclinic.com,pending,$699.39,37d4d2d8-06e9-4304-aa87-cecb84d30a95,Peru
1095,467.0,ALLISTER MELLOWS,amellowscy@vimeo.com,2025-11-06,$127.81,7dac3d2e-cfce-423b-b34c-24c1efa35950,Unknown
1096,122.0,carl lamey,clamey3d@php.net,17 Mar 2025,$500.37,a900e75e-5035-4357-824e-d82f8db6a607,Armenia

##### Handling Duplicates: A glitch caused users to be charged twice. You must use .duplicated() to find identical transactions and .drop_duplicates(keep='first') to refund/remove the errors.

In [19]:
df_dup = df.duplicated()
df_dup

1       False
2       False
3       False
5       False
6       False
        ...
1092    False
1093    False
1094    False
1095    False
1096    False
Length: 930, dtype: bool

In [20]:
df.drop_duplicates(keep='first', inplace=True)
df

,id,customer name,email,purchase date,price,trx,shipping state
1,689.0,kimmy haborn,khabornj4@google.es,pending,$539.17,Unknown,Panama
2,414.0,matthias calcutt,mcalcuttbh@freewebs.com,11/17/2025,$534.17,4a22264d-4c87-4f9d-b4a5-99e343cb768e,Brazil
3,789.0,ALGERNON NIAVES,aniaveslw@wunderground.com,2025-09-20,$345.84,83a9aa51-0a17-4fd8-a7c3-46a87c019f7b,Philippines
5,760.0,hayes kleewein,hkleeweinl3@kickstarter.com,2025-12-30,$275.30,f91b1691-2e28-486d-82eb-1a81cba02f98,Germany
6,97.0,SUSANNE CUMMINS,scummins2o@paypal.com,unknown,$602.31,Unknown,Vietnam
...,...,...,...,...,...,...,...
1092,872.0,shawn hengoed,shengoedo7@ustream.tv,pending,$179.86,506a5235-eec5-493e-ab86-392840d8dd9b,China
1093,88.0,maridel rogeron,mrogeron2f@google.de,unknown,$380.12,0da184d0-4c09-4d6b-8d54-cc0f0980fa0e,Unknown
1094,331.0,britteny euesden,beuesden96@mayoclinic.com,pending,$699.39,37d4d2d8-06e9-4304-aa87-cecb84d30a95,Peru
1095,467.0,ALLISTER MELLOWS,amellowscy@vimeo.com,2025-11-06,$127.81,7dac3d2e-cfce-423b-b34c-24c1efa35950,Unknown
1096,122.0,carl lamey,clamey3d@php.net,17 Mar 2025,$500.37,a900e75e-5035-4357-824e-d82f8db6a607,Armenia

### Data Type Conversions:
##### "Price" is imported as a string (e.g., "$1,200.50"). You must remove the symbols and use pd.to_numeric() to turn it into a float.

In [21]:
df['price'] = df['price'].str.replace(r'\$', '', regex=True).str.replace(',', '', regex=False)
df['price'] = pd.to_numeric(df['price'],errors='coerce')
print(df['price'])

1       539.17
2       534.17
3       345.84
5       275.30
6       602.31
         ...
1092    179.86
1093    380.12
1094    699.39
1095    127.81
1096    500.37
Name: price, Length: 849, dtype: float64

##### Replace the “pending” and “unknown” with the previous datetime

In [22]:
df['purchase date'] = df['purchase date'].replace(['pending','unknown'], pd.NA)
df['purchase date'] = df['purchase date'].ffill()
print(df['purchase date'])

1              <NA>
2        11/17/2025
3        2025-09-20
5        2025-12-30
6        2025-12-30
           ...
1092     2025-06-07
1093     2025-06-07
1094     2025-06-07
1095     2025-11-06
1096    17 Mar 2025
Name: purchase date, Length: 849, dtype: object

##### Convert “purchase date" from messy text into a proper datetime object using pd.to_datetime().

In [24]:
df['purchase date'] = df['purchase date'].astype('string').str.strip()
df['purchase date'] = pd.to_datetime(df['purchase date'],errors='coerce',format='mixed')
print(df['purchase date'])

1             NaT
2      2025-11-17
3      2025-09-20
5      2025-12-30
6      2025-12-30
          ...
1092   2025-06-07
1093   2025-06-07
1094   2025-06-07
1095   2025-11-06
1096   2025-03-17
Name: purchase date, Length: 849, dtype: datetime64[ns]

##### Convert the “purchase date" format from various format into this format “M/D/Y”

In [25]:
df['purchase date'] = df['purchase date'].dt.strftime('%m/%d/%Y')
print(df['purchase date'])

1              NaN
2       11/17/2025
3       09/20/2025
5       12/30/2025
6       12/30/2025
           ...
1092    06/07/2025
1093    06/07/2025
1094    06/07/2025
1095    11/06/2025
1096    03/17/2025
Name: purchase date, Length: 849, dtype: object

##### String Manipulation: The "Names" column has chaotic capitalization and extra spaces. You use .str.title() and .str.strip() to fix this. You must also extract the email domain (e.g., extracting "gmail.com" from "user@gmail.com") using .str.split().

In [26]:
df

,id,customer name,email,purchase date,price,trx,shipping state
1,689.0,kimmy haborn,khabornj4@google.es,NaN,539.17,Unknown,Panama
2,414.0,matthias calcutt,mcalcuttbh@freewebs.com,11/17/2025,534.17,4a22264d-4c87-4f9d-b4a5-99e343cb768e,Brazil
3,789.0,ALGERNON NIAVES,aniaveslw@wunderground.com,09/20/2025,345.84,83a9aa51-0a17-4fd8-a7c3-46a87c019f7b,Philippines
5,760.0,hayes kleewein,hkleeweinl3@kickstarter.com,12/30/2025,275.30,f91b1691-2e28-486d-82eb-1a81cba02f98,Germany
6,97.0,SUSANNE CUMMINS,scummins2o@paypal.com,12/30/2025,602.31,Unknown,Vietnam
...,...,...,...,...,...,...,...
1092,872.0,shawn hengoed,shengoedo7@ustream.tv,06/07/2025,179.86,506a5235-eec5-493e-ab86-392840d8dd9b,China
1093,88.0,maridel rogeron,mrogeron2f@google.de,06/07/2025,380.12,0da184d0-4c09-4d6b-8d54-cc0f0980fa0e,Unknown
1094,331.0,britteny euesden,beuesden96@mayoclinic.com,06/07/2025,699.39,37d4d2d8-06e9-4304-aa87-cecb84d30a95,Peru
1095,467.0,ALLISTER MELLOWS,amellowscy@vimeo.com,11/06/2025,127.81,7dac3d2e-cfce-423b-b34c-24c1efa35950,Unknown
1096,122.0,carl lamey,clamey3d@php.net,03/17/2025,500.37,a900e75e-5035-4357-824e-d82f8db6a607,Armenia

In [29]:
df['customer name'] = df['customer name'].str.title().str.strip()
print(df['customer name'])

1           Kimmy Haborn
2       Matthias Calcutt
3        Algernon Niaves
5         Hayes Kleewein
6        Susanne Cummins
              ...
1092       Shawn Hengoed
1093     Maridel Rogeron
1094    Britteny Euesden
1095    Allister Mellows
1096          Carl Lamey
Name: customer name, Length: 849, dtype: object

In [31]:
df['email_domain'] = df['email'].str.strip().str.split('@').str[1]
print(df['email_domain'])

1              google.es
2           freewebs.com
3       wunderground.com
5        kickstarter.com
6             paypal.com
              ...
1092          ustream.tv
1093           google.de
1094      mayoclinic.com
1095           vimeo.com
1096             php.net
Name: email_domain, Length: 849, dtype: object