# Messy University Admissions Database Rescue
##### The Scenario: You act as a university data analyst. The legacy admissions portal crashed during a system migration, and the backup applicant data is a mess. You must clean the "Applicant Records" dataset.

In [2]:
import pandas as pd
df = pd.read_csv('admissions_messy.csv')
df

,Application ID,Applicant Name,Email,Intended Major,High School State,Application Fee,Submission Date
0,1352.0,wanda DOE,wdoe@gmail.com,Math,NV,$297.91,pending
1,1689.0,PETER JONES,pjones@edu.org,Journalism,NaN,"$1,939.68",08/14/2023
2,1485.0,wanda MAXIMOFF,wmaximoff@yahoo.com,Math,NaN,$277.90,2023/06/06
3,1388.0,PETER Parker,pparker@yahoo.com,Agriculture,AZ,$370.25,2023-02-24
4,1031.0,bruce rogers,brogers@stark.com,Physics,NV,$53.93,"Oct 16, 2023"
...,...,...,...,...,...,...,...
1045,1330.0,diana MAXIMOFF,dmaximoff@edu.org,NaN,AZ,$862.30,10-18-2023
1046,1466.0,STEVE Allen,sallen@edu.org,Journalism,NaN,$389.22,10-20-2023
1047,1121.0,Charlie ROGERS,crogers@stark.com,History,AZ,"$1,746.27","Aug 17, 2023"
1048,1299.0,peter Wayne,pwayne@dailybugle.com,Journalism,KS,$689.05,2023-06-06
1049,NaN,CHARLIE Brown,cbrown@yahoo.com,Business,KS,"$1,875.22",unknown

##### Handling Missing Data: The dataset is riddled with NaNs. You must use .dropna() to remove rows completely missing an Application ID. You will use .fillna() to replace missing Intended Major and High School State values with "Unknown" that were lost during the export.

In [3]:
df.dropna(subset=['Application ID'],inplace = True)
df

,Application ID,Applicant Name,Email,Intended Major,High School State,Application Fee,Submission Date
0,1352.0,wanda DOE,wdoe@gmail.com,Math,NV,$297.91,pending
1,1689.0,PETER JONES,pjones@edu.org,Journalism,NaN,"$1,939.68",08/14/2023
2,1485.0,wanda MAXIMOFF,wmaximoff@yahoo.com,Math,NaN,$277.90,2023/06/06
3,1388.0,PETER Parker,pparker@yahoo.com,Agriculture,AZ,$370.25,2023-02-24
4,1031.0,bruce rogers,brogers@stark.com,Physics,NV,$53.93,"Oct 16, 2023"
...,...,...,...,...,...,...,...
1044,1087.0,John Stone,jstone@gmail.com,Computer Science,KS,"$1,582.76",2023/05/27
1045,1330.0,diana MAXIMOFF,dmaximoff@edu.org,NaN,AZ,$862.30,10-18-2023
1046,1466.0,STEVE Allen,sallen@edu.org,Journalism,NaN,$389.22,10-20-2023
1047,1121.0,Charlie ROGERS,crogers@stark.com,History,AZ,"$1,746.27","Aug 17, 2023"
1048,1299.0,peter Wayne,pwayne@dailybugle.com,Journalism,KS,$689.05,2023-06-06

In [4]:
df['Intended Major'] = df['Intended Major'].fillna('Unknown')
df['High School State'] = df['High School State'].fillna('Unknown')
df

,Application ID,Applicant Name,Email,Intended Major,High School State,Application Fee,Submission Date
0,1352.0,wanda DOE,wdoe@gmail.com,Math,NV,$297.91,pending
1,1689.0,PETER JONES,pjones@edu.org,Journalism,Unknown,"$1,939.68",08/14/2023
2,1485.0,wanda MAXIMOFF,wmaximoff@yahoo.com,Math,Unknown,$277.90,2023/06/06
3,1388.0,PETER Parker,pparker@yahoo.com,Agriculture,AZ,$370.25,2023-02-24
4,1031.0,bruce rogers,brogers@stark.com,Physics,NV,$53.93,"Oct 16, 2023"
...,...,...,...,...,...,...,...
1044,1087.0,John Stone,jstone@gmail.com,Computer Science,KS,"$1,582.76",2023/05/27
1045,1330.0,diana MAXIMOFF,dmaximoff@edu.org,Unknown,AZ,$862.30,10-18-2023
1046,1466.0,STEVE Allen,sallen@edu.org,Journalism,Unknown,$389.22,10-20-2023
1047,1121.0,Charlie ROGERS,crogers@stark.com,History,AZ,"$1,746.27","Aug 17, 2023"
1048,1299.0,peter Wayne,pwayne@dailybugle.com,Journalism,KS,$689.05,2023-06-06

##### Handling Duplicates: A server glitch caused applicants to accidentally submit identical applications twice. You must use .duplicated() to find identical application rows and .drop_duplicates(keep='first') to remove the errors and keep only the original submission.

In [5]:
df_dup = df.duplicated()
df_dup

0       False
1       False
2       False
3       False
4       False
        ...
1044    False
1045    False
1046    False
1047    False
1048     True
Length: 943, dtype: bool

In [6]:
df.drop_duplicates(keep='first', inplace=True)
df

,Application ID,Applicant Name,Email,Intended Major,High School State,Application Fee,Submission Date
0,1352.0,wanda DOE,wdoe@gmail.com,Math,NV,$297.91,pending
1,1689.0,PETER JONES,pjones@edu.org,Journalism,Unknown,"$1,939.68",08/14/2023
2,1485.0,wanda MAXIMOFF,wmaximoff@yahoo.com,Math,Unknown,$277.90,2023/06/06
3,1388.0,PETER Parker,pparker@yahoo.com,Agriculture,AZ,$370.25,2023-02-24
4,1031.0,bruce rogers,brogers@stark.com,Physics,NV,$53.93,"Oct 16, 2023"
...,...,...,...,...,...,...,...
1043,1871.0,Arthur Wayne,awayne@gmail.com,Art,NJ,"$1,619.10",05-07-2023
1044,1087.0,John Stone,jstone@gmail.com,Computer Science,KS,"$1,582.76",2023/05/27
1045,1330.0,diana MAXIMOFF,dmaximoff@edu.org,Unknown,AZ,$862.30,10-18-2023
1046,1466.0,STEVE Allen,sallen@edu.org,Journalism,Unknown,$389.22,10-20-2023
1047,1121.0,Charlie ROGERS,crogers@stark.com,History,AZ,"$1,746.27","Aug 17, 2023"

### Data Type Conversions:
##### Application Fee is imported as a string (e.g., "$150.50"). You must remove the symbols and use pd.to_numeric() to turn it into a float.

In [7]:
df['Application Fee'] = df['Application Fee'].str.replace(r'\$', '', regex=True).str.replace(',', '', regex=False)
df['Application Fee'] = pd.to_numeric(df['Application Fee'], errors='coerce')
print(df['Application Fee'])

0        297.91
1       1939.68
2        277.90
3        370.25
4         53.93
         ...
1043    1619.10
1044    1582.76
1045     862.30
1046     389.22
1047    1746.27
Name: Application Fee, Length: 898, dtype: float64

##### Replace “pending” and “unknown” text entries in the dates with the previous valid datetime (forward filling).

In [8]:
df['Submission Date'] = df['Submission Date'].replace(['pending', 'unknown'], pd.NA)
df['Submission Date'] = df['Submission Date'].ffill()
print(df['Submission Date'])

0               <NA>
1         08/14/2023
2         2023/06/06
3         2023-02-24
4       Oct 16, 2023
            ...
1043      05-07-2023
1044      2023/05/27
1045      10-18-2023
1046      10-20-2023
1047    Aug 17, 2023
Name: Submission Date, Length: 898, dtype: object

##### Convert Submission Date from messy text into a proper datetime object using pd.to_datetime().

In [9]:
df['Submission Date'] = df['Submission Date'].astype('string').str.strip()
df['Submission Date'] = pd.to_datetime(df['Submission Date'],errors='coerce',format='mixed')
print(df['Submission Date'])

0             NaT
1      2023-08-14
2      2023-06-06
3      2023-02-24
4      2023-10-16
          ...
1043   2023-05-07
1044   2023-05-27
1045   2023-10-18
1046   2023-10-20
1047   2023-08-17
Name: Submission Date, Length: 898, dtype: datetime64[ns]

##### Convert the Submission Date format from various mixed formats into a uniform "M/D/Y" format.

In [10]:
df['Submission Date'] = df['Submission Date'].dt.strftime('%m/%d/%Y')
print(df['Submission Date'])

0              NaN
1       08/14/2023
2       06/06/2023
3       02/24/2023
4       10/16/2023
           ...
1043    05/07/2023
1044    05/27/2023
1045    10/18/2023
1046    10/20/2023
1047    08/17/2023
Name: Submission Date, Length: 898, dtype: object

##### String Manipulation: The Applicant Name column has chaotic capitalization and extra spaces. You will use .str.title() and .str.strip() to fix this. You must also extract the email domain (e.g., extracting "yahoo.com" from "student@yahoo.com") using .str.split() to see which email providers are most common.

In [11]:
df['Applicant Name'] = df['Applicant Name'].str.title().str.strip()
print(df['Applicant Name'])

0            Wanda Doe
1          Peter Jones
2       Wanda Maximoff
3         Peter Parker
4         Bruce Rogers
             ...
1043      Arthur Wayne
1044        John Stone
1045    Diana Maximoff
1046       Steve Allen
1047    Charlie Rogers
Name: Applicant Name, Length: 898, dtype: object

In [14]:
df['email_domain'] = df['Email'].str.strip().str.split('@').str[1]
df['email_domain'].value_counts()

email_domain
gmail.com         144
stark.com         137
dailybugle.com    129
yahoo.com         125
outlook.com       124
edu.org           123
skynet.com        116
Name: count, dtype: int64