# Global Meteorite Landings Tracker
##### The Scenario: You act as junior planetary scientists analyzing historical data of meteorite impacts and discoveries on Earth.

In [4]:
import pandas as pd
df = pd.read_csv('meteorites.csv')
df

,name,mass_grams,classification,fall_status,region,year
0,Allan Hills 84001,1930,Martian,Found,Antarctica,1984
1,Hoba,60000000,Iron,Found,Africa,1920
2,Campo del Cielo,50000000,Iron,Found,South America,1576
3,Tagish Lake,10000,Carbonaceous Chondrite,Fell,North America,2000
4,Chelyabinsk,1000000,Ordinary Chondrite,Fell,Russia,2013
5,Sikhote-Alin,23000000,Iron,Fell,Russia,1947
6,Nantan,9500000,Iron,Found,China,1516
7,Yamato 000593,13700,Martian,Found,Antarctica,2000
8,Elephant Moraine 79001,7900,Martian,Found,Antarctica,1979
9,Sahara 97096,26500,Enstatite Chondrite,Found,Sahara,1997
10,Acfer 059,200,Chondrite,Found,Sahara,1989
11,Gibeon,26000000,Iron,Found,Africa,1836
12,Canyon Diablo,30000000,Iron,Found,North America,1891
13,Peekskill,12400,Ordinary Chondrite,Fell,North America,1992
14,Queen Alexandra Range 93148,84000,Pallasite,Found,Antarctica,1993
15,Gao-Guenie,100000,Ordinary Chondrite,Fell,Sahara,1960
16,Murchison,100000,Carbonaceous Chondrite,Fell,Australia,1969

##### Data Structures: You separate out specific columns, like the mass_grams, to see how it behaves as an isolated 1D Series compared to the broader 2D DataFrame context.

In [23]:
mass = df['mass_grams']
mass

0         1930
1     60000000
2     50000000
3        10000
4      1000000
5     23000000
6      9500000
7        13700
8         7900
9        26500
10         200
11    26000000
12    30000000
13       12400
14       84000
15      100000
16      100000
Name: mass_grams, dtype: int64

In [20]:
df.loc[:,['mass_grams']]

    mass_grams
0         1930
1     60000000
2     50000000
3        10000
4      1000000
5     23000000
6      9500000
7        13700
8         7900
9        26500
10         200
11    26000000
12    30000000
13       12400
14       84000
15      100000
16      100000

##### Initial Data Inspection: Before doing anything, you must run .info() and .describe() to understand the sheer volume of data and check for missing values. You will use .head() to see the layout of the columns, and use .value_counts() to see which meteorite classification types (e.g., Chondrite, Iron) are the most frequently found.

In [60]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            17 non-null     object
 1   mass_grams      17 non-null     int64
 2   classification  17 non-null     object
 3   fall_status     17 non-null     object
 4   region          17 non-null     object
 5   year            17 non-null     int64
dtypes: int64(2), object(4)
memory usage: 948.0+ bytes

         mass_grams         year
count  1.700000e+01    17.000000
mean   1.175627e+07  1915.411765
std    1.927873e+07   146.639464
min    2.000000e+02  1516.000000
25%    1.240000e+04  1920.000000
50%    1.000000e+05  1979.000000
75%    2.300000e+07  1993.000000
max    6.000000e+07  2013.000000

In [81]:
df.head()

,name,mass_grams,classification,fall_status,region,year
0,Allan Hills 84001,1930,Martian,Found,Antarctica,1984
1,Hoba,60000000,Iron,Found,Africa,1920
2,Campo del Cielo,50000000,Iron,Found,South America,1576
3,Tagish Lake,10000,Carbonaceous Chondrite,Fell,North America,2000
4,Chelyabinsk,1000000,Ordinary Chondrite,Fell,Russia,2013

In [5]:
df['classification'].value_counts()

classification
Iron                      6
Martian                   3
Ordinary Chondrite        3
Carbonaceous Chondrite    2
Enstatite Chondrite       1
Chondrite                 1
Pallasite                 1
Name: count, dtype: int64

### Indexing and Selection: 
##### Column/Label/Integer: Use dictionary-style selection to grab the fall_status column (whether it was seen falling or just found later). Use .iloc[] to extract the top 5 heaviest meteorites based on their sorted row position.

In [6]:
df.loc[:,['fall_status']]

   fall_status
0        Found
1        Found
2        Found
3         Fell
4         Fell
5         Fell
6        Found
7        Found
8        Found
9        Found
10       Found
11       Found
12       Found
13        Fell
14       Found
15        Fell
16        Fell

In [8]:
heaviest = df.sort_values(by="mass_grams",ascending=False)
heaviest.iloc[0:5]

,name,mass_grams,classification,fall_status,region,year
1,Hoba,60000000,Iron,Found,Africa,1920
2,Campo del Cielo,50000000,Iron,Found,South America,1576
12,Canyon Diablo,30000000,Iron,Found,North America,1891
11,Gibeon,26000000,Iron,Found,Africa,1836
5,Sikhote-Alin,23000000,Iron,Fell,Russia,1947

##### Filtering: Apply multiple boolean conditions using & and | to find meteorites that are both greater than 50,000 grams in mass and were discovered in a specific region (e.g., "Antarctica" or "Sahara").

In [28]:
filters = (df["mass_grams"] > 50000) & (
            (df["region"] == "Antarctica") | (df["region"] == "Sahara")
         )
filtered = df[filters]
filtered

,name,mass_grams,classification,fall_status,region,year
14,Queen Alexandra Range 93148,84000,Pallasite,Found,Antarctica,1993
15,Gao-Guenie,100000,Ordinary Chondrite,Fell,Sahara,1960

##### Data I/O: You start by loading the raw data using pd.read_csv(). Later, you will export your filtered findings using .to_excel() or .to_json() for a museum curation team to use for an upcoming exhibit.

In [30]:
filtered.to_json("meteorites.json", orient="records")
print("Success")

Success