# Global Earthquake Activity Tracker
##### The Scenario: You act as junior seismologists analyzing recent global earthquake data.

In [9]:
import pandas as pd
df = pd.read_csv('earthquake.csv')
df

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2026-03-10T06:28:05.052Z,37.448900,140.995500,69.630,4.60,mb,57,94,2.4100,0.78,...,2026-03-10T06:55:58.040Z,"3 km S of Namie, Japan",earthquake,3.08,6.9340,0.054000,104.0,reviewed,us,us
1,2026-03-10T06:09:51.071Z,62.340000,-151.493000,97.800,2.60,ml,51,60,0.4000,0.60,...,2026-03-10T07:27:39.040Z,"39 km N of Skwentna, Alaska",earthquake,3.40,3.3504,0.100000,4.0,automatic,ak,ak
2,2026-03-10T05:52:01.570Z,42.145333,-120.967167,6.890,3.25,ml,8,83,0.2554,0.09,...,2026-03-10T07:22:18.082Z,"36 km E of Bonanza, Oregon",earthquake,0.31,0.9400,0.142146,24.0,reviewed,uw,uw
3,2026-03-10T05:20:04.300Z,-23.345500,171.564500,10.000,5.00,mb,50,127,3.8640,0.78,...,2026-03-10T05:38:31.040Z,southeast of the Loyalty Islands,earthquake,10.17,1.9250,0.071000,64.0,reviewed,us,us
4,2026-03-10T04:46:26.147Z,61.808000,-148.696000,19.300,3.60,ml,170,29,0.1000,1.20,...,2026-03-10T08:05:51.269Z,"4 km NE of Sutton-Alpine, Alaska",earthquake,1.60,1.4125,0.200000,24.0,automatic,ak,ak
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432,2026-03-03T02:12:10.368Z,54.253600,-162.330400,17.504,2.60,ml,14,219,0.7190,0.72,...,2026-03-03T02:33:34.040Z,"89 km S of King Cove, Alaska",earthquake,5.72,12.7950,0.115000,10.0,reviewed,us,us
433,2026-03-03T02:04:04.032Z,53.980900,-163.751600,33.218,2.70,ml,20,217,0.6650,0.87,...,2026-03-03T02:14:06.040Z,"99 km SSW of False Pass, Alaska",earthquake,4.16,14.0810,0.115000,10.0,reviewed,us,us
434,2026-03-03T01:40:34.692Z,52.407400,-170.018200,21.445,3.00,ml,13,305,0.3910,0.41,...,2026-03-03T02:09:09.040Z,"98 km SW of Nikolski, Alaska",earthquake,12.05,18.0880,0.105000,12.0,reviewed,us,us
435,2026-03-03T00:23:40.452Z,58.337000,-155.067000,114.600,2.90,ml,109,43,0.0000,0.60,...,2026-03-03T04:59:51.040Z,"92 km NNW of Karluk, Alaska",earthquake,3.80,1.3154,0.400000,79.0,reviewed,ak,ak
436,2026-03-03T00:11:43.467Z,25.289300,124.890600,10.000,5.00,mww,67,91,1.0840,0.50,...,2026-03-03T04:53:04.040Z,"67 km NW of Hirara, Japan",earthquake,5.65,1.7730,0.066000,22.0,reviewed,us,us

In [3]:
df.columns

Index(['time', 'latitude', 'longitude', 'depth', 'mag', 'magType', 'nst',
       'gap', 'dmin', 'rms', 'net', 'id', 'updated', 'place', 'type',
       'horizontalError', 'depthError', 'magError', 'magNst', 'status',
       'locationSource', 'magSource'],
      dtype='object')

##### Data Structures: You separate out specific columns, like the magnitude, to see how it behaves as an isolated 1D Series compared to the 2D DataFrame context.

In [8]:
 magnitude = df['mag']
 magnitude

0      4.60
1      2.60
2      3.25
3      5.00
4      3.60
       ...
432    2.60
433    2.70
434    3.00
435    2.90
436    5.00
Name: mag, Length: 437, dtype: float64

In [12]:
df.loc[:,['mag']]

      mag
0    4.60
1    2.60
2    3.25
3    5.00
4    3.60
..    ...
432  2.60
433  2.70
434  3.00
435  2.90
436  5.00

[437 rows x 1 columns]

##### Initial Data Inspection: Before doing anything, you must run .info() and .describe() to understand the sheer volume of data, use .head() to see the layout, and use .value_counts() to see which regions have the most frequent seismic activity.

In [14]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 437 entries, 0 to 436
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   time             437 non-null    object
 1   latitude         437 non-null    float64
 2   longitude        437 non-null    float64
 3   depth            437 non-null    float64
 4   mag              437 non-null    float64
 5   magType          437 non-null    object
 6   nst              437 non-null    int64
 7   gap              437 non-null    int64
 8   dmin             435 non-null    float64
 9   rms              437 non-null    float64
 10  net              437 non-null    object
 11  id               437 non-null    object
 12  updated          437 non-null    object
 13  place            437 non-null    object
 14  type             437 non-null    object
 15  horizontalError  427 non-null    float64
 16  depthError       437 non-null    float64
 17  magError         434 non-null    float64
 18  magNst           435 non-null    float64
 19  status           437 non-null    object
 20  locationSource   437 non-null    object
 21  magSource        437 non-null    object
dtypes: float64(10), int64(2), object(10)
memory usage: 75.2+ KB

,latitude,longitude,depth,mag,nst,gap,dmin,rms,horizontalError,depthError,magError,magNst
count,437.000000,437.000000,437.000000,437.000000,437.000000,437.000000,435.000000,437.000000,427.000000,437.000000,434.000000,435.000000
mean,34.776555,-37.736996,50.419789,3.663249,47.750572,139.059497,1.624267,0.655337,6.980475,4.472189,0.121309,43.450575
std,26.430813,134.684577,99.165012,0.989571,38.852397,79.240235,3.606685,0.303047,5.858383,4.346007,0.076124,57.204212
min,-59.386800,-179.980800,-1.530000,2.500000,5.000000,14.000000,0.000000,0.070200,0.070000,0.000000,0.008535,3.000000
25%,19.420500,-155.221500,10.000000,2.720000,20.000000,70.000000,0.357500,0.450000,2.800000,1.874000,0.073000,13.000000
50%,43.549200,-93.414700,11.086000,3.300000,37.000000,130.000000,0.734000,0.680000,6.100000,2.536000,0.100000,25.000000
75%,52.404000,125.381900,43.102000,4.500000,59.000000,201.000000,1.472000,0.870000,9.575000,6.487200,0.148000,52.500000
max,73.227100,179.979500,618.136000,6.400000,236.000000,322.000000,46.843000,1.450000,57.400000,31.610000,0.500000,663.000000

In [16]:
df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2026-03-10T06:28:05.052Z,37.448900,140.995500,69.63,4.60,mb,57,94,2.4100,0.78,...,2026-03-10T06:55:58.040Z,"3 km S of Namie, Japan",earthquake,3.08,6.9340,0.054000,104.0,reviewed,us,us
1,2026-03-10T06:09:51.071Z,62.340000,-151.493000,97.80,2.60,ml,51,60,0.4000,0.60,...,2026-03-10T07:27:39.040Z,"39 km N of Skwentna, Alaska",earthquake,3.40,3.3504,0.100000,4.0,automatic,ak,ak
2,2026-03-10T05:52:01.570Z,42.145333,-120.967167,6.89,3.25,ml,8,83,0.2554,0.09,...,2026-03-10T07:22:18.082Z,"36 km E of Bonanza, Oregon",earthquake,0.31,0.9400,0.142146,24.0,reviewed,uw,uw
3,2026-03-10T05:20:04.300Z,-23.345500,171.564500,10.00,5.00,mb,50,127,3.8640,0.78,...,2026-03-10T05:38:31.040Z,southeast of the Loyalty Islands,earthquake,10.17,1.9250,0.071000,64.0,reviewed,us,us
4,2026-03-10T04:46:26.147Z,61.808000,-148.696000,19.30,3.60,ml,170,29,0.1000,1.20,...,2026-03-10T08:05:51.269Z,"4 km NE of Sutton-Alpine, Alaska",earthquake,1.60,1.4125,0.200000,24.0,automatic,ak,ak

In [20]:
df['region'] = df['place'].str.split(',').str[-1].str.strip()
df['region']

0                                 Japan
1                                Alaska
2                                Oregon
3      southeast of the Loyalty Islands
4                                Alaska
                     ...
432                              Alaska
433                              Alaska
434                              Alaska
435                              Alaska
436                               Japan
Name: region, Length: 437, dtype: object

In [21]:
df['region'].value_counts()

region
Alaska                              195
Russia                               21
Puerto Rico                          16
New Mexico                           16
CA                                   15
                                   ...
Greece                                1
Bouvet Island region                  1
Colombia                              1
southeast of the Loyalty Islands      1
Croatia                               1
Name: count, Length: 64, dtype: int64

### Indexing and Selection: 
##### Column/Label/Integer: Use dictionary-style selection to grab the 'Location' column. Use .iloc[] to extract the top 5 largest earthquakes based on row position.

In [23]:
df.loc[:,['locationSource']]

    locationSource
0               us
1               ak
2               uw
3               us
4               ak
..             ...
432             us
433             us
434             us
435             ak
436             us

[437 rows x 1 columns]

In [21]:
largest = df.sort_values(by="mag",ascending=False)
largest.iloc[0:5]

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
341,2026-03-04T17:54:36.733Z,52.2664,176.3634,10.000,6.4,mww,115,50,1.359,0.88,...,2026-03-09T18:04:41.347Z,"224 km ESE of Attu Station, Alaska",earthquake,5.15,1.820,0.030,104.0,reviewed,us,us
228,2026-03-06T14:27:47.626Z,-11.5475,163.1628,8.682,6.3,mww,51,45,3.793,0.93,...,2026-03-07T14:55:34.181Z,"181 km SE of Kirakira, Solomon Islands",earthquake,3.71,5.154,0.047,44.0,reviewed,us,us
428,2026-03-03T04:56:46.093Z,2.0420,96.7387,18.000,6.2,mww,236,32,1.112,0.79,...,2026-03-05T02:02:47.917Z,"62 km SE of Sinabang, Indonesia",earthquake,7.93,1.686,0.062,25.0,reviewed,us,us
14,2026-03-09T23:03:54.405Z,40.5650,14.0671,381.687,6.0,mww,151,29,0.601,0.75,...,2026-03-10T05:30:56.531Z,"12 km W of Anacapri, Italy",earthquake,6.25,4.506,0.045,47.0,reviewed,us,us
89,2026-03-08T17:08:42.581Z,51.6210,159.3956,16.000,5.9,mww,102,44,1.477,0.90,...,2026-03-09T17:37:12.320Z,"160 km SSE of Vilyuchinsk, Russia",earthquake,9.12,1.843,0.048,41.0,reviewed,us,us

##### Filtering: Apply multiple boolean conditions using & and | to find earthquakes that are both greater than magnitude 6.0 and occurred in a specific region (e.g., "Japan" or “Texas”).

In [25]:
filters = (df["mag"] > 6.0) & (
    (df['place'] == "Japan" | (df['place'] == "Alaska")
)

filtered = df[filters]
filtered

SyntaxError: '(' was never closed (2158782909.py, line 1)

##### Data I/O: You start by loading the data using pd.read_csv(). Later, you will export their filtered findings using .to_excel() or .to_json() for a web team to use.

In [18]:
filtered.to_json("earthquake.json", orient="records")
print("Success")

Success